{
  "Resources": {
    "slsAwsDevCognitoAuthRole": {
      "Type": "AWS::IAM::Role",
      "DependsOn": [
        "slsAwsDevIdentityPool"
      ],
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Federated": "cognito-identity.amazonaws.com"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "cognito-identity.amazonaws.com:aud": {
                    "Ref": "slsAwsDevIdentityPool"
                  }
                }
              }
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "cognitoauth",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:InvokeFunction"
                  ],
                  "Resource": {
                    "Fn::GetAtt": [
                      "slsAwsDevApiLambdaFunction",
                      "Arn"
                    ]
                  }
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "cognito-sync:*",
                    "execute-api:*"
                  ],
                  "Resource": [
                    "*"
                  ]
                }
              ]
            }
          }
        ]
      }
    },
    "slsAwsDevCognitoUnauthRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "cognito-identity.amazonaws.com"
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "cognitounauth",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:InvokeFunction"
                  ],
                  "Resource": {
                    "Fn::GetAtt": [
                      "slsAwsDevApiLambdaFunction",
                      "Arn"
                    ]
                  }
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "cognito-sync:*"
                  ],
                  "Resource": [
                    "*"
                  ]
                }
              ]
            }
          }
        ]
      }
    },
    "slsAwsDevIdentityPool": {
      "Type": "AWS::Cognito::IdentityPool",
      "Properties": {
        "IdentityPoolName": "slsAwsDevIdentityPool",
        "AllowUnauthenticatedIdentities": true,
        "CognitoIdentityProviders": [
          {
            "ClientId": {
              "Ref": "slsAwsDevUserPoolClient"
            },
            "ProviderName": {
              "Fn::GetAtt": [
                "slsAwsDevUserPool",
                "ProviderName"
              ]
            }
          }
        ]
      }
    },
    "slsAwsDevIdentityPoolRoleAttachment": {
      "DependsOn": [
        "slsAwsDevIdentityPool",
        "slsAwsDevCognitoUnauthRole",
        "slsAwsDevCognitoAuthRole"
      ],
      "Type": "AWS::Cognito::IdentityPoolRoleAttachment",
      "Properties": {
        "IdentityPoolId": {
          "Ref": "slsAwsDevIdentityPool"
        },
        "Roles": {
          "authenticated": {
            "Fn::GetAtt": [
              "slsAwsDevCognitoAuthRole",
              "Arn"
            ]
          },
          "unauthenticated": {
            "Fn::GetAtt": [
              "slsAwsDevCognitoUnauthRole",
              "Arn"
            ]
          }
        }
      }
    },
    "slsAwsDevUserPool": {
      "Type": "AWS::Cognito::UserPool",
      "Properties": {
        "UsernameAttributes": [
          "email"
        ],
        "AutoVerifiedAttributes": [
          "email"
        ],
        "EmailVerificationSubject": "Your verification code",
        "EmailVerificationMessage": "Your verification code is {####}.",
        "UserPoolName": "slsAwsDevUserPool"
      }
    },
    "slsAwsDevUserPoolClient": {
      "Type": "AWS::Cognito::UserPoolClient",
      "Properties": {
        "ClientName": "slsAwsDevUserPoolClient",
        "GenerateSecret": false,
        "RefreshTokenValidity": 365,
        "UserPoolId": {
          "Ref": "slsAwsDevUserPool"
        }
      }
    },
    "slsAwsDevApiLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "DependsOn": [
        "slsAwsDevApiLambdaExecutionRole"
      ],
      "Properties": {
        "Code": "./src/server/api/index.js",
        "Role": {
          "Fn::GetAtt": [
            "slsAwsDevApiLambdaExecutionRole",
            "Arn"
          ]
        },
        "Runtime": "nodejs8.10"
      }
    },
    "slsAwsDevApiLambdaExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "root",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "dynamodb:DescribeTable",
                    "dynamodb:Query",
                    "dynamodb:Scan",
                    "dynamodb:GetItem",
                    "dynamodb:PutItem",
                    "dynamodb:UpdateItem",
                    "dynamodb:DeleteItem"
                  ],
                  "Resource": "*"
                }
              ]
            }
          }
        ]
      }
    }
  },
  "Outputs": {
    "userPoolId": {
      "Description": "User pool ID",
      "Value": {
        "Ref": "slsAwsDevUserPool"
      }
    },
    "identityPoolId": {
      "Description": "Identity pool ID",
      "Value": {
        "Ref": "slsAwsDevIdentityPool"
      }
    },
    "clientId": {
      "Description": "Client id for the user pool appclient",
      "Value": {
        "Ref": "slsAwsDevUserPoolClient"
      }
    },
    "apiFunctionArn": {
      "Description": "Api Lambd fn arn",
      "Value": {
        "Fn::GetAtt": [
          "slsAwsDevApiLambdaFunction",
          "Arn"
        ]
      }
    }
  }
}
