export const LOGIN_FORM_MODULE_ID = 'LOGIN_FORM_MODULE_ID'
export const SIGN_UP_FORM_MODULE_ID = 'SIGN_UP_FORM_MODULE_ID'
export const VERIFY_ACCOUNT_FORM_MODULE_ID = 'VERIFY_ACCOUNT_FORM_MODULE_ID'

export const CREATE_PROJECT_FORM_MODULE_ID = 'CREATE_PROJECT_FORM_MODULE_ID'
export const VIEW_PROJECT_MODULE_ID = 'VIEW_PROJECT_MODULE_ID'
export const PENDING_PROJECTS_LIST_MODULE_ID = 'PENDING_PROJECTS_LIST_MODULE_ID'
export const ACTIVE_PROJECTS_LIST_MODULE_ID = 'ACTIVE_PROJECTS_LIST_MODULE_ID'
export const PLEDGE_PROJECT_FORM_MODULE_ID = 'PLEDGE_PROJECT_FORM_MODULE_ID'

export const HOW_IT_WORKS_MODULE_ID = 'HOW_IT_WORKS_MODULE_ID'
