version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: yarn lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
