export const INIT_API_RECORD_REQUEST = 'INIT_API_REQUEST'
export const INIT_API_LIST_REQUEST = 'INIT_API_REQUEST'

export const API_LIST_REQUEST_SUCCESS = 'API_LIST_REQUEST_SUCCESS'
export const API_LIST_REQUEST_ERROR = 'API_LIST_REQUEST_ERROR'

export const API_RECORD_REQUEST_SUCCESS = 'API_RECORD_REQUEST_SUCCESS'
export const API_RECORD_REQUEST_ERROR = 'API_RECORD_REQUEST_ERROR'
