export const INIT_API_RECORD_REQUEST = 'INIT_API_REQUEST'
export const INIT_API_LIST_REQUEST = 'INIT_API_REQUEST'

export const API_REQUEST_LIST_SUCCESS = 'API_REQUEST_LIST_SUCCESS'
export const API_REQUEST_LIST_ERROR = 'API_REQUEST_LIST_ERROR'

export const API_REQUEST_RECORD_SUCCESS = 'API_REQUEST_RECORD_SUCCESS'
export const API_REQUEST_RECORD_ERROR = 'API_REQUEST_RECORD_ERROR'
