export const SUBMIT_FORM = 'actionId/SUBMIT_FORM'
export const SUBMIT_FORM_COMPLETE = 'actionId/SUBMIT_FORM_COMPLETE'
export const CLEAR_FORM = 'actionId/CLEAR_FORM'
export const CHANGE_INPUT = 'actionId/CHANGE_INPUT'
export const SET_FORM_ERRORS = 'actionId/SET_FORM_ERRORS'
export const CLEAR_FORM_ERRORS = 'actionId/CLEAR_FORM_ERRORS'
