export const LOGIN_ROUTE_ID = 'LOGIN_ROUTE_ID'
export const SIGN_UP_ROUTE_ID = 'SIGN_UP_ROUTE_ID'
export const VERIFY_ACCOUNT_ROUTE_ID = 'VERIFY_ACCOUNT_ROUTE_ID'

export const DASHBOARD_ROUTE_ID = 'DASHBOARD_ROUTE_ID'

export const CREATE_PROJECT_ROUTE_ID = 'CREATE_PROJECT_ROUTE_ID'

export const VIEW_PROJECT_ROUTE_ID = 'VIEW_PROJECT_ROUTE_ID'
