export const CREATE_PROJECT = 'CREATE_PROJECT'
export const GET_PROJECT = 'GET_PROJECT'
export const SAVE_PARTIAL_DARE_FORM = 'SAVE_PARTIAL_DARE_FORM'
export const CLEAR_PARTIAL_FORM_KEYS = 'CLEAR_PARTIAL_FORM_KEYS'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const REJECT_ACTIVE_PROJECT = 'REJECT_ACTIVE_PROJECT'

export const PLEDGE_PROJECT = 'PLEDGE_PROJECT'
export const GET_PLEDGED_PROJECTS = 'GET_PLEDGED_PROJECTS'

export const AUDIT_PROJECT = 'AUDIT_PROJECT'

export const GET_ACTIVE_PROJECTS = 'GET_ACTIVE_PROJECTS'
export const GET_PENDING_PROJECTS = 'GET_PENDING_PROJECTS'

export const AUTH_TWITCH = 'AUTH_TWITCH'
