export const CREATE_PROJECT = 'CREATE_PROJECT'
export const GET_PROJECT = 'GET_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'

export const PLEDGE_PROJECT = 'PLEDGE_PROJECT'
export const GET_PLEDGED_PROJECTS = 'GET_PLEDGED_PROJECTS'

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const GET_FAVORITES_LIST = 'GET_FAVORITES_LIST'

export const AUDIT_PROJECT = 'AUDIT_PROJECT'

export const GET_ACTIVE_PROJECTS = 'GET_ACTIVE_PROJECTS'
export const GET_PENDING_PROJECTS = 'GET_PENDING_PROJECTS'
